name: NetFramework

on: [push]
 
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore packages
      run: nuget restore GeckoUI.sln
    - name: Restore via dotnet
      run: dotnet restore GeckoUI.sln
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Copy files
      run: copy D:\a\geckoui\geckoui\packages\Geckofx60.32.60.0.44\lib\net45\ D:\a\geckoui\geckoui\GeckoUI\
    - name: Make dir
      run: mkdir D:\a\geckoui\geckoui\GeckoUI\bin\Release
    - name: Copy files (2)
      run: copy D:\a\geckoui\geckoui\packages\Geckofx60.32.60.0.44\lib\net45\ D:\a\geckoui\geckoui\GeckoUI\bin\Release
    - name: List dir
      run: ls
    - name: Build with MSBuild
      run: msbuild GeckoUI.sln -restore -p:Configuration=Release
